const state = {
  users: [{ name: "", points: 0, id: 0 }],
  user: "",
  themes: [
    "Lugares turisticos de europa como: Torre Eafiel",
    "Cantantes de salsa como: Mark antony",
    "Capitales de euro tales como: Madrid",
    "Cantantes de ranchera como: Vicente Fernandez",
    "Platos colombianos como: la changua",
    "Villancicos como: Ana nanita nana",
    "Marcas de ropa colombiana como: Abril",
    "Banco colombianos como: Banco de occidente",
    "Lugares turisticos colombianos como: Guatape",
    "Mascotas como: un gato",
    "Deportes como: ciclismo",
    "Marcas de motos como: yamaha",
    "Marcas de carros americanas como: chevrolet",
    "Equipos de futbol alemanes como: Bayer de Munich",
    "Peliculas de terror como: anabelle",
    "Deportes en equipo como: futbol",
    "Juegos en linea como: fornite",
    "Series de anime como: naruto",
    "Series de netflix como: la casa de papel",
    "Super heroes de marvel como: capitan america",
    "Peliculas de viajes en el tiempo como: volver al futuro",
    "Grupos de salsa como: grupo niche",
    "Grupos de rock como: Queen",
    "Marcas de computadores como: Apple",
    "Marcas de neveras como: Mabe",
    "Supermercados como: carulla",
    "Cantantes de vallenato como: Diomendez Díaz",
    "Platos de mar como: causuela de maricos",
    "Novelas colombianas como: vecinos",
    "Marcas de bicicletas como: gw",
    "Frutas en la gama de colores del amarillo como: banano",
    "Frutas en la gama de colores del rojo como: manzana",
    "Redes sociales como: fabebook",
    "Paises de america latina como: Colombia",
    "Paises de europa como: Francia",
    "Paises de asia como: China",
    "Paises de africa como: Nigeria",
    "Villanos en peliculas de super heroes como: joker",
    "Marcas de esmaltes como: masglo",
    "Montañas como: Everest",
    "Nevados como: Nevado de ruiz",
    "Platos de navidad como: la natilla",
    "Tipos de cerveza como: ipa",
    "Marcas de cerveza que se venda en colombia como: poker",
    "Juegos de mesa como: parques",
    "Marcas de maletas como: totto",
    "Frutas en la gama del color verde",
    "Pueblos de Colombia como: Lerida",
    "Lugares turisticos del mundo como: La torre de pisa",
    "Nombres de presidentes de paises del mundo como: Juan Manuel Santos",
    "Platos del mundo como: Ramen",
    "Monedas del mundo como: COP",
    "Gentilicio del mundo como: Colombianos",
    "Piedras preciosas como: El diamante",
    "Nombres de emisoras como: Candela",
    "Nombres de aeropuertos como: El dorado",
    "Tipo de calzado como: Tennis",
    "Deportistas Colombianos",
  ],
  mode: 1,
};

export default state;
