const state = {
  users: [{ name: "", points: 0, id: 0 }],
  user: "",
  themes: [
    "Cantantes de salsa como: Mark antony",
    "Cantes de ranchera como: Vicente Fernandez",
    "Platos colombianos como: la changua",
    "Villancicos como: Ana nanita nana",
    "Marcas de ropa colombiana como: Abril",
    "Banco colombianos como: Banco de occidente",
    "Lugares turisticos colombianos como: Guatape",
    "Mascotas como: un gato",
    "Deportes como: ciclismo",
    "Marcas de motos como: yamaha",
    "Marcas de carros americanas como: chevrolet",
    "Equipos de futbol alemanes como: Bayer de Munich",
    "Peliculas de terror como: anabelle",
    "Juegos en linea como: fornite",
    "Series de anime como: naruto",
    "Series de netflix como: la casa de papel",
    "Super heroes de marvel como: capitan america",
    "Peliculas de viajes en el tiempo como: volver al futuro",
    "Grupos de salsa como: grupo niche",
    "Grupos de rock como: Queen",
    "Marcas de computadores como: Apple",
    "Marcas de neveras como: Mabe",
    "Supermercados como: carulla",
    "Cantantes de vallenato como: Diomendez Díaz",
    "Platos de mar como: causuela de maricos",
    "Novelas colombianas como: vecinos",
    "Marcas de bicicletas como: gw",
    "Frutas en la gama de colores del amarillo como: banano",
    "Frutas en la gama de colores del rojo como: banano",
    "Redes sociales como: fabebook",
    "Paises de america latina como: Colombia",
    "Paises de europa como: Francia",
    "Paises de asia como: China",
    "Paises de africa como: Nigeria",
    "Villanos en peliculas de super heroes como: joker",
    "Marcas de esmaltes como: masglo",
    "Platos de navidad como: la natilla",
    "Tipos de cerveza como: ipa",
    "Marcas de cerveza que se venda en colombia como: poker",
    "Juegos de mesa como: parques",
    "Marcas de maletas como: totto",
  ],
};

export default state;
